[versions]
ktor = "2.3.2"                     # https://ktor.io/
datetime = "0.4.0"                 # https://github.com/Kotlin/kotlinx-datetime
serialization = "1.5.1"            # https://github.com/Kotlin/kotlinx.serialization
kotlin = "1.9.0"
logback = "1.4.8"                  # https://logback.qos.ch/download.html
node-plugin = "5.0.0"              # https://github.com/node-gradle/gradle-node-plugin
coroutines = "1.7.2"               # https://github.com/Kotlin/kotlinx.coroutines/
exposed = "0.41.1"                 # https://github.com/JetBrains/Exposed
telegram-bot = "6.0.7"             # https://github.com/kotlin-telegram-bot/kotlin-telegram-bot
shadow-plugin = "8.1.1"            # https://github.com/johnrengelman/shadow
sqlite = "3.42.0.0"                # https://github.com/xerial/sqlite-jdbc
clikt = "4.0.0"                    # https://ajalt.github.io/clikt/
immutable = "0.3.5"                # https://github.com/Kotlin/kotlinx.collections.immutable
protobuf-plugin = "0.9.3"          # https://github.com/google/protobuf-gradle-plugin
protobuf = "3.23.2"
grpc = "1.55.1"                    # https://github.com/grpc/grpc
grpc-kotlin = "1.3.0"              # https://github.com/grpc/grpc-kotlin

[libraries]

ktor-client-cio        = { version.ref = "ktor", group = "io.ktor", name = "ktor-client-cio" }
ktor-client-auth       = { version.ref = "ktor", group = "io.ktor", name = "ktor-client-auth" }
ktor-client-websockets = { version.ref = "ktor", group = "io.ktor", name = "ktor-client-websockets" }
ktor-client-logging    = { version.ref = "ktor", group = "io.ktor", name = "ktor-client-logging" }

ktor-serialization-kotlinx-json = { version.ref = "ktor", group = "io.ktor", name = "ktor-serialization-kotlinx-json" }

ktor-server-tests = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-tests" }
ktor-server-autoHeadResponse    = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-auto-head-response" }
ktor-server-auth                = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-auth" }
ktor-server-callLogging         = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-call-logging" }
ktor-server-contentNegotiation  = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-content-negotiation" }
ktor-server-core                = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-core" }
ktor-server-cors                = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-cors" }
ktor-server-defaultHeaders      = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-default-headers" }
ktor-server-netty               = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-netty" }
ktor-server-statusPages         = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-status-pages" }
ktor-server-websockets          = { version.ref = "ktor", group = "io.ktor", name = "ktor-server-websockets" }



kotlinx-datetime           = { version.ref = "datetime", group = "org.jetbrains.kotlinx", name = "kotlinx-datetime" }
kotlinx-serialization-json = { version.ref = "serialization", group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json" }
kotlinx-serialization-properties = { version.ref = "serialization", group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-properties" }
kotlinx-serialization-protobuf = { version.ref = "serialization", group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-protobuf" }
kotlinx-coroutines-core    = { version.ref = "coroutines", group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core" }
kotlinx-collections-immutable = { version.ref = "immutable", group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable"}


kotlin-serialization-plugin = { version.ref = "kotlin", group = "org.jetbrains.kotlin", name = "kotlin-serialization" }
kotlin-gradle-plugin        = { version.ref = "kotlin", group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin" }
kotlin-junit                = { version.ref = "kotlin", group = "org.jetbrains.kotlin", name = "kotlin-test-junit" }

exposed-core = { version.ref = "exposed", group = "org.jetbrains.exposed", name = "exposed-core"}
exposed-dao = { version.ref = "exposed", group = "org.jetbrains.exposed", name = "exposed-dao"}
exposed-jdbc = { version.ref = "exposed", group = "org.jetbrains.exposed", name = "exposed-jdbc"}

logback = { version.ref = "logback", group = "ch.qos.logback", name = "logback-classic" }

telegram-bot = { version.ref = "telegram-bot", group = "io.github.kotlin-telegram-bot.kotlin-telegram-bot", name = "telegram" }

db-sqlite = { version.ref = "sqlite", group = "org.xerial", name = "sqlite-jdbc" }

cli = { version.ref = "clikt", group = "com.github.ajalt.clikt", name = "clikt" }

grpc-netty = { version.ref = "grpc", group = "io.grpc", name = "grpc-netty-shaded" }
grpc-protobuf = { version.ref = "grpc", group = "io.grpc", name = "grpc-protobuf" }
grpc-stub = { version.ref = "grpc-kotlin", group = "io.grpc", name = "grpc-kotlin-stub" }
grpc-gen-java = { version.ref = "grpc", group = "io.grpc", name = "protoc-gen-grpc-java" }
grpc-gen-kotlin = { version.ref = "grpc-kotlin", group = "io.grpc", name = "protoc-gen-grpc-kotlin" }

protobuf = { version.ref = "protobuf", group = "com.google.protobuf", name = "protobuf-kotlin" }

[plugins]

ktor = { id = "io.ktor.plugin",  version.ref = "ktor" }
node = { id = "com.github.node-gradle.node", version.ref = "node-plugin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow-plugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobuf-plugin" }
